# Site settings
title: Mario's Site
description: These are notes for a student who started his professional career as a hacker and could be useful for someone else.
#baseurl: "/hackingnotes" # the subpath of your site, e.g. /blog
#url: "http://mvc1009.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mario Valiente
user_description: I am an ethical hacker and CTF enthusiast eager to learn and improve professionally.
user_title: Ethical Hacker
email: mvc1009@gmail.com
twitter_username: lorem_ipsum
github_username:  mvc1009
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
